<?php defined( 'ABSPATH' ) || exit; ?>

<?php
/**
 * !!! DO NOT EDIT THIS FILE !!!
 *
 * Do not edit templates in the plugin folder, since all your changes will be
 * lost after the plugin update. Read the following article to learn how to
 * change this template or create a custom one:
 *
 * https://getshortcodes.com/docs/posts/#built-in-templates
 */
?>

<div class="su-posts su-posts-template-single-post">

	<?php if ( $su_posts->have_posts() ) : ?>

		<?php while ( $su_posts->have_posts() ) : ?>

			<?php $su_posts->the_post(); ?>

			<div id="su-post-<?php the_ID(); ?>" class="su-post">

				<h1 class="su-post-title"><?php the_title(); ?></h1>

				<div class="su-post-meta">

					<?php esc_html_e( 'Posted', 'shortcodes-ultimate' ); ?>:
					<?php the_time( get_option( 'date_format' ) ); ?>

					<?php if ( have_comments() || comments_open() ) : ?>

					<span>|</span>
					<a href="<?php comments_link(); ?>" class="su-post-comments-link">
						<?php comments_number( __( '0 comments', 'shortcodes-ultimate' ), __( '1 comment', 'shortcodes-ultimate' ), __( '% comments', 'shortcodes-ultimate' ) ); ?>
					</a>

					<?php endif; ?>

				</div>

				<div class="su-post-content">
					<?php the_content(); ?>
				</div>

			</div>

		<?php break; ?><?php endwhile; ?>

	<?php else : ?>

		<p><?php esc_html_e( 'Posts not found', 'shortcodes-ultimate' ); ?></p>

	<?php endif; ?>

</div>
